[#IOPID-94] Add first LC openapi
pagopa/io-backend pull request #1006
Opened 2023-04-17 14:52 UTC by gquadrati

#### List of Changes

Added `api_lollipop_first_consumer.yaml`

#### Motivation and Context

Expose first LC endpoint

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [x] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-04-19 05:39 UTC, shadowsheep1 requested changes

2023-04-19 08:05 UTC, gquadrati commented on api_lollipop_first_consumer.yaml
> +            $ref: "#/definitions/ProblemJson"
401 does not return a ProblemJson, see https://github.com/pagopa/io-backend/blob/0ea5db0e7b776cc26474fe66d851e0e30db912ec/api_backend.yaml#L42

2023-04-19 08:21 UTC, shadowsheep1 commented on api_lollipop_first_consumer.yaml
> +            $ref: "#/definitions/ProblemJson"
Yep, sorry. I explain better what I mean. With the provided hint I get the response decoder correctly as I expect it to be with the response types provided above. It's correct to have a "`401`" without response body 👍

2023-04-19 09:17 UTC, shadowsheep1 approved these changes
LGTM

2023-04-20 08:28 UTC, BurnedMarshal approved these changes
LGTM. Is correct that all the openapi specification on root folder are not validated from openapi linter? step `validate_api_specification`

2023-04-20 08:31 UTC, gquadrati commented
> LGTM. Is correct that all the openapi specification on root folder are not validated from openapi linter? step `validate_api_specification`

I see that too.. I think we should remove the one in root folder and move to openapi folder, but we need to synchronize the change with the app.

2023-04-20 08:31 UTC, merged