[#IOPID-257] Handle new login type on `acs` callback
pagopa/io-backend pull request #1023
Opened 2023-06-13 08:31 UTC by gquadrati

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-06-15 09:13 UTC, BurnedMarshal requested changes

2023-06-15 12:57 UTC, gquadrati commented on README.md
> +| LV_TOKEN_DURATION_IN_SECONDS           | The number of seconds a session token is considered valid if LV is enabled        | int    |
Thanks, done in [077a783](https://github.com/pagopa/io-backend/pull/1023/commits/077a7837dc34d47ea67530a6805c2be4edf54aa0)

2023-06-15 12:57 UTC, gquadrati commented on src/utils/fastLogin.ts
> +    loginType: _req.header("x-pagopa-login-type"),
Beccata 😄  Done in [077a783](https://github.com/pagopa/io-backend/pull/1023/commits/077a7837dc34d47ea67530a6805c2be4edf54aa0)

2023-06-15 12:58 UTC, gquadrati commented on src/controllers/__tests__/authenticationController.test.ts
> +    ${undefined}              | ${false}       | ${tokenDurationSecs}
Right, done in [077a783](https://github.com/pagopa/io-backend/pull/1023/commits/077a7837dc34d47ea67530a6805c2be4edf54aa0)

2023-06-15 12:58 UTC, gquadrati commented on src/config.ts
> +  : DEFAULT_LV_TOKEN_DURATION_IN_SECONDS;
Thanks, done in [077a783](https://github.com/pagopa/io-backend/pull/1023/commits/077a7837dc34d47ea67530a6805c2be4edf54aa0)

2023-06-16 08:32 UTC, BurnedMarshal requested changes

2023-06-16 08:32 UTC, BurnedMarshal commented on src/controllers/authenticationController.ts
> +    // With FF set to BETA or CANARY, only whitelisted CF can use the LV functionality (the token TTL is reduced if login type is `LV`).
This seems to be wrong. If the FF is set to `CANARY` the LV is disabled for all the users on the current implementation:
```typescrypt
export const getIsUserElegibleForfastLogin = (
  betaTesters: ReadonlyArray<FiscalCode>,
  FF_FastLogin: FeatureFlag
) =>
  getIsUserEligibleForNewFeature<FiscalCode>(
    (fiscalCode) => betaTesters.includes(fiscalCode),
    (_fiscalCode) => false, // <----- CANARY
    FF_FastLogin
  );
```

2023-06-16 08:35 UTC, BurnedMarshal commented on src/controllers/authenticationController.ts
> +    // With FF set to BETA or CANARY, only whitelisted CF can use the LV functionality (the token TTL is reduced if login type is `LV`).
Nope my bad, in the inner implementation canary includes betas user, sorry. But is not very clear is an hidden behaviour
```
case "CANARY":
        return isUserCanary(i) || isUserBeta(i);
```

2023-06-19 08:21 UTC, BurnedMarshal approved these changes
LGTM

2023-06-19 08:25 UTC, BurnedMarshal commented
/azp run

2023-06-19 09:52 UTC, merged