[#IOPID-351] Refactor session verification for LV
pagopa/io-backend pull request #1031
Opened 2023-06-23 08:20 UTC by gquadrati

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-06-23 08:40 UTC, BurnedMarshal commented on src/types/assertionRef.ts
> +});
This object will be stored one time for user (milions of records) on Redis. Maybe we should consider a more compact format to consume less memory. For example:
```typescript
export const StoredAssertionRefV1 = t.type({
  a: AssertionRef,
  v: t.literal(1),
});
```
Or alternatively  we can improve the encoder decoder to produce a JSON with that form (I prefer this option)

2023-06-27 10:22 UTC, BurnedMarshal commented on src/types/assertionRef.ts
> +      LollipopData.decode
Maybe is equivalent, but the error message could be more consistent if types composition will be needed.
```suggestion
      (data) => LollipopData.validate(data, _context)
```

2023-06-27 10:50 UTC, BurnedMarshal requested changes

2023-06-27 10:50 UTC, BurnedMarshal commented on src/services/__tests__/redisSessionStorage.test.ts
> +    expect(result).toEqual(E.right(true));
To verify the logic add a couple of expect like:
```
expect(mockGet).toHaveBeenNthCalledWith(1, `KEYS-${aValidUser.fiscal_code}`);
expect(mockSmembers).toBeCalledWith(aValidUser.fiscal_code);
expect(mockGet).toHaveBeenNthCalledWith(2, `SESSIONINFO-${aValidUser.session_token}`)
```

2023-06-27 10:50 UTC, BurnedMarshal commented on src/services/__tests__/redisSessionStorage.test.ts
> +  it("should return false if login type is LEGACY and user has no active sessions", async () => {
There is another scenario that should be tested. The SessionInfo has not an expire but the Session has it. We should test when the SMembers return a `SESSIONINFO` value and the next session get doesn't find a session.

2023-06-27 10:50 UTC, BurnedMarshal commented on src/services/__tests__/redisSessionStorage.test.ts
> +    expect(response).toEqual(E.right(O.some(anAssertionRef)));
kudos, much better :D

2023-06-28 09:36 UTC, gquadrati commented on src/services/redisSessionStorage.ts
> +  public async isUserLogged(
In that case the login type would be `LEGACY`

2023-06-28 09:37 UTC, gquadrati commented on src/controllers/notificationController.ts
> +              () => this.sessionStorage.isUserLogged(data.message.fiscal_code),
Done in [4386d13](https://github.com/pagopa/io-backend/pull/1031/commits/4386d13b6f1a620054db37e2b4ec05d012dc6157)

2023-06-28 09:51 UTC, gquadrati commented on src/types/assertionRef.ts
> +export type LollipopDataT = t.TypeOf<typeof LollipopData>;
I think it's more readable. Anyway, removed in [d771338](https://github.com/pagopa/io-backend/pull/1031/commits/d7713385dcdf430a89c21350858db77c2e46cbfd)

2023-06-28 09:51 UTC, gquadrati commented on src/services/redisSessionStorage.ts
>              `${lollipopFingerprintPrefix}${user.fiscal_code}`,
Done in [d771338](https://github.com/pagopa/io-backend/pull/1031/commits/d7713385dcdf430a89c21350858db77c2e46cbfd)

2023-06-28 09:51 UTC, gquadrati commented on src/services/redisSessionStorage.ts
> +  // eslint-disable-next-line @typescript-eslint/member-ordering
Done in [d771338](https://github.com/pagopa/io-backend/pull/1031/commits/d7713385dcdf430a89c21350858db77c2e46cbfd)

2023-07-06 08:11 UTC, gquadrati commented
Replaced by https://github.com/pagopa/io-backend/pull/1036

2023-07-06 08:11 UTC, closed without merging