[IOPID-1399] Add opex dashboard for "api_backend"
pagopa/io-backend pull request #1095
Opened 2024-01-23 09:27 UTC by lucacavallaro

#### List of Changes

1. Add Azure Dashboard to monitor `api_backend.yaml` endpoints

#### Motivation and Context

This dashboard enables us to monitor core endpoints like (`/profiles` that was recently modified for the unique e-mail enforcement feature and `/messages`)

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [x] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-01-23 10:20 UTC, gquadrati requested changes
We need to add GH actions

2024-01-23 17:04 UTC, arcogabbo requested changes

2024-01-23 17:04 UTC, arcogabbo commented on api_backend.yaml
why are we doing this changes? the referenced spec in `config.yaml` is on `generated` directory

2024-01-23 17:04 UTC, arcogabbo commented on .opex/api_backend/env/prod/config.yaml
> +    /profile:
this should fix the error in the pipeline
```suggestion
    /api/v1/profile:
```

2024-01-23 17:09 UTC, lucacavallaro commented on api_backend.yaml
the file reference in `config.yaml` is `api_backend.yaml` from the root, the `schema` property is not supported on `openapi 2.0`

2024-01-30 10:42 UTC, gquadrati commented on api_backend.yaml
>          required: true
Actually, the openapi in master branch is not valid, so I close this comment.

2024-02-01 15:46 UTC, arcogabbo commented
`api_backend.yaml` invalid spec was fixed in #1099 @lucacavallaro

2024-02-02 15:32 UTC, gquadrati commented
@lucacavallaro, as mentioned by @arcogabbo, we have addressed the specifications. 
Once conflicts are resolved, we can proceed with the merge.

2024-02-07 12:44 UTC, gquadrati approved these changes

2024-02-07 13:48 UTC, merged