[#IOCOM-1031] refactor for remote content configuration
pagopa/io-backend pull request #1103
Opened 2024-02-19 16:59 UTC by acuiuli

#### List of Changes

- [refactor for remote content configuration](https://github.com/pagopa/io-backend/pull/1103/commits/dd9a3abdaaca5451002f0849d4c5a7f1fa643521)
- [fixed problem with generate app messages client](https://github.com/pagopa/io-backend/pull/1103/commits/c807dd30ba445becebeb6661f267abd9b93ee3ac)
- [fixed all tests after remote content configuration refactor](https://github.com/pagopa/io-backend/pull/1103/commits/71156ae09b94d063ca06fe67aea19c07035bbc4c)
- [removed duplicated code in tests](https://github.com/pagopa/io-backend/pull/1103/commits/560f885c7a4be8319c257cc2ea8c6bcaa4797ba0)
- [openapi bundle fix](https://github.com/pagopa/io-backend/pull/1103/commits/6cab957c11c35322fb33aed9b1f92644164e88b6)

#### Motivation and Context

This is a refactor made due to the new remote content configuration management 
To get the remote content configuration a new getRCConfiguration api is called using the configuration_id inside the ThirdPartyData.
Also all the PN specific code has been modified to use the configuration_id instead of the service_id

#### How Has This Been Tested?

unit test

#### Screenshots (if appropriate):

#### Types of changes

- [x] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-02-20 18:05 UTC, lucacavallaro commented
@acuiuli can you add the "motivation and context" behind this change?

2024-02-21 09:49 UTC, Garma00 commented on src/controllers/messagesController.ts
> +            ResponseErrorInternal("Cannot get remote content configuration")
I think we can be more specific here, we cannot retrieve the configuration because of the missing `configuration_id`

2024-02-22 11:04 UTC, michaeldisaro requested changes

2024-02-22 11:09 UTC, acuiuli commented on src/clients/third-party-service-client.ts
> +  (apiKey: RCAuthenticationConfig) =>
I agree, I renamed it as `authConfig`

2024-02-22 13:10 UTC, michaeldisaro approved these changes

2024-02-22 13:15 UTC, michaeldisaro commented
/azp run

2024-02-22 13:53 UTC, merged