refactor: remove MIT Voucher functionality
pagopa/io-backend pull request #1158
Opened 2024-10-18 09:18 UTC by salvatorelaiso

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-10-22 17:15 UTC, gquadrati requested changes

2024-10-22 17:15 UTC, gquadrati commented on openapi/api_mit_voucher.template.yaml
Remove `generated/api_mit_voucher.yaml` as well

2024-10-23 08:18 UTC, salvatorelaiso commented on openapi/api_mit_voucher.template.yaml
Resolved in [2f57c7f](https://github.com/pagopa/io-backend/pull/1158/commits/2f57c7fc77253f4d85cc3c90caf514d049bec48c)

2024-10-24 09:48 UTC, gquadrati approved these changes

2024-10-24 09:54 UTC, merged