[#ICC-87] New Third party get message and attachments endpoints definition
pagopa/io-backend pull request #892
Opened 2022-06-01 12:32 UTC by gquadrati

This PR depends on [io-fn-commons #ICC-87](https://github.com/pagopa/io-functions-commons/pull/275)

#### List of Changes

- add new `getThirdPartyMessage` and `getThirdPartyMessageAttachment` openapi definitions
- add new `getThirdPartyMessage` and `getThirdPartyMessageAttachment` in MessageController, returning `501 - Not Implemented`

#### Motivation and Context

Expose new endpoint for retrieving Third Party message details and attachments

#### How Has This Been Tested?

io-mock

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2022-06-01 15:37 UTC, fabriziopapi requested changes

2022-06-01 15:37 UTC, fabriziopapi commented on src/utils/responses.ts
> + * Returns an unauthorized error response with status code 501.
```suggestion
 * Returns a Not Implemented error response with status code 501.
```

2022-06-06 15:47 UTC, fabriziopapi commented
LGTM appena modificati i puntamenti per la fn-commons

2022-06-06 16:42 UTC, gquadrati commented
> LGTM appena modificati i puntamenti per la fn-commons

I've updated fn-commons refs, but I need an approval form merging it

2022-06-06 17:11 UTC, fabriziopapi approved these changes

2022-06-07 08:22 UTC, gquadrati commented on api_backend.yaml
> +      summary: Eetrieve Third Party message
```suggestion
      summary: Retrieve Third Party message
```

2022-06-08 13:03 UTC, merged